/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "ChemicalData.h"

std::map<std::string, MAtomType> MAtomType::_map =
{
    /**
     * Data from http://code.google.com/p/jquery-pte/downloads/detail?name=jquery.pte.json
     * because it was easy to parse and more or less complete. values are not used anyway.
     * backbone and sidechain atoms are getting some strange values for surface calculation.
     * The values here should probably support that.
     * Starting from silver the elements do not occur regularly in the PDB. Sorted alphabetically from here on.
     */
    {"?", MAtomType("?", "Unknown", 0, 0, 0)},
    {"C", MAtomType("C", "Carbon", 6, 0.91, 12.01)},
    {"O", MAtomType("O", "Oxygen", 8, 0.65, 16.00)},
    {"H", MAtomType("H", "Hydrogen", 1, 2.08, 1.01)},
    {"N", MAtomType("N", "Nitrogen", 7, 0.92, 14.01)},
    {"S", MAtomType("S", "Sulfur", 16, 1.27, 32.07)},
    {"P", MAtomType("P", "Phosphorus", 15, 1.28, 30.97)},
    {"MG", MAtomType("MG", "Magnesium", 12, 1.60, 24.30)},
    {"SE", MAtomType("SE", "Selenium", 34, 1.40, 78.96)},
    {"ZN", MAtomType("ZN", "Zinc", 30, 1.38, 65.39)},
    {"D", MAtomType("D", "Deuterium", 1, 2.08, 2.014)},     // radius just taken from hydrogen wrong. but well...
    {"CA", MAtomType("CA", "Calcium", 20, 1.97, 40.08)},
    {"B", MAtomType("B", "Boron", 5, 0.98, 10.81)},
    {"F", MAtomType("F", "Fluorine", 9, 0.57, 19.00)},
    {"I", MAtomType("I", "Iodine", 53, 1.32, 126.90)},
    {"K", MAtomType("K", "Potassium", 19, 2.35, 39.10)},
    {"U", MAtomType("U", "Uranium", 92, 1.38, 238.03)},
    {"V", MAtomType("V", "Vanadium", 23, 1.34, 50.94)},
    {"W", MAtomType("W", "Tungsten", 74, 1.41, 183.85)},
    {"Y", MAtomType("Y", "Yttrium", 39, 1.78, 88.91)},
    {"AG", MAtomType("AG", "Silver", 47, 1.44, 107.87)},
    {"AL", MAtomType("AL", "Aluminum", 13, 1.43, 26.98)},
    {"AR", MAtomType("AR", "Argon", 18, 0.88, 39.95)},
    {"AS", MAtomType("AS", "Arsenic", 33, 1.39, 74.92)},
    {"AU", MAtomType("AU", "Gold", 79, 1.46, 196.97)},
    {"BA", MAtomType("BA", "Barium", 56, 2.22, 137.33)},
    {"BE", MAtomType("BE", "Beryllium", 4, 1.12, 9.01)},
    {"BI", MAtomType("BI", "Bismuth", 83, 1.70, 208.98)},
    {"BR", MAtomType("BR", "Bromine", 35, 1.12, 79.90)},
    {"CD", MAtomType("CD", "Cadmium", 48, 1.71, 112.41)},
    {"CE", MAtomType("CE", "Cerium", 58, 1.81, 140.12)},
    {"CL", MAtomType("CL", "Chlorine", 17, 0.97, 35.45)},
    {"CO", MAtomType("CO", "Cobalt", 27, 1.25, 58.93)},
    {"CR", MAtomType("CR", "Chromium", 24, 1.30, 52.00)},
    {"CS", MAtomType("CS", "Cesium", 55, 2.67, 132.91)},
    {"CU", MAtomType("CU", "Copper", 29, 1.28, 63.55)},
    {"ER", MAtomType("ER", "Erbium", 68, 1.78, 167.26)},
    {"EU", MAtomType("EU", "Europium", 63, 1.99, 151.97)},
    {"FE", MAtomType("FE", "Iron", 26, 1.26, 55.85)},
    {"GA", MAtomType("GA", "Gallium", 31, 1.41, 69.72)},
    {"GD", MAtomType("GD", "Gadolinium", 64, 1.80, 157.25)},
    {"HF", MAtomType("HF", "Hafnium", 72, 1.67, 178.49)},
    {"HG", MAtomType("HG", "Mercury", 80, 1.60, 200.59)},
    {"HO", MAtomType("HO", "Holmium", 67, 1.79, 164.93)},
    {"IN", MAtomType("IN", "Indium", 49, 1.66, 114.82)},
    {"IR", MAtomType("IR", "Iridium", 77, 1.36, 192.22)},
    {"KR", MAtomType("KR", "Krypton", 36, 1.03, 83.80)},
    {"LA", MAtomType("LA", "Lanthanum", 57, 1.38, 138.91)},
    {"LI", MAtomType("LI", "Lithium", 3, 1.55, 6.94)},
    {"LU", MAtomType("LU", "Lutetium", 71, 1.75, 174.97)},
    {"MN", MAtomType("MN", "Manganese", 25, 1.35, 54.94)},
    {"MO", MAtomType("MO", "Molybdenum", 42, 1.39, 95.94)},
    {"NA", MAtomType("NA", "Sodium", 11, 1.90, 22.99)},
    {"NE", MAtomType("NE", "Neon", 10, 0.51, 20.18)},
    {"NI", MAtomType("NI", "Nickel", 28, 1.24, 58.69)},
    {"OS", MAtomType("OS", "Osmium", 76, 1.35, 190.20)},
    {"PA", MAtomType("PA", "Protactinium", 91, 1.61, 231.04)},
    {"PB", MAtomType("PB", "Lead", 82, 1.75, 207.20)},
    {"PD", MAtomType("PD", "Palladium", 46, 1.37, 106.42)},
    {"PR", MAtomType("PR", "Praseodymium", 59, 1.82, 140.91)},
    {"PT", MAtomType("PT", "Platinum", 78, 1.39, 195.08)},
    {"RB", MAtomType("RB", "Rubidium", 37, 2.48, 85.47)},
    {"RE", MAtomType("RE", "Rhenium", 75, 1.37, 186.21)},
    {"RH", MAtomType("RH", "Rhodium", 45, 1.34, 102.91)},
    {"RU", MAtomType("RU", "Ruthenium", 44, 1.34, 101.07)},
    {"SB", MAtomType("SB", "Antimony", 51, 1.59, 121.76)},
    {"SI", MAtomType("SI", "Silicon", 14, 1.32, 28.09)},
    {"SM", MAtomType("SM", "Samarium", 62, 1.81, 150.36)},
    {"SN", MAtomType("SN", "Tin", 50, 1.62, 118.71)},
    {"SR", MAtomType("SR", "Strontium", 38, 2.15, 87.62)},
    {"TA", MAtomType("TA", "Tantalum", 73, 1.49, 180.95)},
    {"TB", MAtomType("TB", "Terbium", 65, 1.80, 158.93)},
    {"TE", MAtomType("TE", "Tellurium", 52, 1.42, 127.60)},
    {"TL", MAtomType("TL", "Thallium", 81, 1.71, 204.38)},
    {"XE", MAtomType("XE", "Xenon", 54, 1.24, 131.29)},
    {"YB", MAtomType("YB", "Ytterbium", 70, 1.94, 173.04)},
    {"ZR", MAtomType("ZR", "Zirconium", 40, 1.60, 91.22)}
};

std::map<std::string, ChemicalPropertiesResidue> ChemicalPropertiesResidue::_map =
{
    {"HOH", ChemicalPropertiesResidue("X", "HOH", "WATER", ResidueType::water )},

    {"LEU", ChemicalPropertiesResidue("L", "LEU", "LEUCINE", ResidueType::withPolarHydrogen )} ,
    {"ALA", ChemicalPropertiesResidue("A", "ALA", "ALANINE", ResidueType::withPolarHydrogen )} ,
    {"GLY", ChemicalPropertiesResidue("G", "GLY", "GLYCINE", ResidueType::withPolarHydrogen )} ,
    {"VAL", ChemicalPropertiesResidue("V", "VAL", "VALINE", ResidueType::withPolarHydrogen )} ,
    {"GLU", ChemicalPropertiesResidue("E", "GLU", "GLUTAMIC ACID", ResidueType::withPolarHydrogen )} ,
    {"SER", ChemicalPropertiesResidue("S", "SER", "SERINE", ResidueType::withPolarHydrogen )} ,
    {"LYS", ChemicalPropertiesResidue("K", "LYS", "LYSINE", ResidueType::withPolarHydrogen )} ,
    {"ASP", ChemicalPropertiesResidue("D", "ASP", "ASPARTIC ACID", ResidueType::withPolarHydrogen )} ,
    {"ILE", ChemicalPropertiesResidue("I", "ILE", "ISOLEUCINE", ResidueType::withPolarHydrogen )} ,
    {"THR", ChemicalPropertiesResidue("T", "THR", "THREONINE", ResidueType::withPolarHydrogen )} ,
    {"ARG", ChemicalPropertiesResidue("R", "ARG", "ARGININE", ResidueType::withPolarHydrogen )} ,
    {"PRO", ChemicalPropertiesResidue("P", "PRO", "PROLINE", ResidueType::noPolarHydrogen )} ,
    {"ASN", ChemicalPropertiesResidue("N", "ASN", "ASPARAGINE", ResidueType::withPolarHydrogen )} ,
    {"PHE", ChemicalPropertiesResidue("F", "PHE", "PHENYLALANINE", ResidueType::withPolarHydrogen )} ,
    {"GLN", ChemicalPropertiesResidue("Q", "GLN", "GLUTAMINE", ResidueType::withPolarHydrogen )} ,
    {"TYR", ChemicalPropertiesResidue("Y", "TYR", "TYROSINE", ResidueType::withPolarHydrogen )} ,
    {"HIS", ChemicalPropertiesResidue("H", "HIS", "HISTIDINE", ResidueType::withPolarHydrogen )} ,
    {"MET", ChemicalPropertiesResidue("M", "MET", "METHIONINE", ResidueType::withPolarHydrogen )} ,
    {"CYS", ChemicalPropertiesResidue("C", "CYS", "CYSTEINE", ResidueType::withPolarHydrogen )} ,
    {"TRP", ChemicalPropertiesResidue("W", "TRP", "TRYPTOPHAN", ResidueType::withPolarHydrogen )} ,
    {"MSE", ChemicalPropertiesResidue("X", "MSE", "SELENOMETHIONINE", ResidueType::withPolarHydrogen )} ,
    {"HYP", ChemicalPropertiesResidue("X", "HYP", "4-HYDROXYPROLINE", ResidueType::noPolarHydrogen )} ,
    {"SEP", ChemicalPropertiesResidue("X", "SEP", "PHOSPHOSERINE", ResidueType::withPolarHydrogen )} ,
    {"TPO", ChemicalPropertiesResidue("X", "TPO", "PHOSPHOTHREONINE", ResidueType::withPolarHydrogen )} ,
    {"DAL", ChemicalPropertiesResidue("X", "DAL", "D-ALANINE", ResidueType::withPolarHydrogen )} ,
    {"ABA", ChemicalPropertiesResidue("X", "ABA", "ALPHA-AMINOBUTYRIC ACID", ResidueType::withPolarHydrogen )} ,
    {"MLY", ChemicalPropertiesResidue("X", "MLY", "N-DIMETHYL-LYSINE", ResidueType::withPolarHydrogen )} ,
    {"PCA", ChemicalPropertiesResidue("X", "PCA", "PYROGLUTAMIC ACID", ResidueType::withPolarHydrogen )} ,
    {"CGU", ChemicalPropertiesResidue("X", "CGU", "GAMMA-CARBOXY-GLUTAMIC ACID", ResidueType::withPolarHydrogen )} ,
    {"PTR", ChemicalPropertiesResidue("X", "PTR", "O-PHOSPHOTYROSINE", ResidueType::withPolarHydrogen )} ,
    {"GHP", ChemicalPropertiesResidue("X", "GHP", "(2R)-AMINO(4-HYDROXYPHENYL)ETHANOIC ACID", ResidueType::withPolarHydrogen )} ,
    {"DBB", ChemicalPropertiesResidue("X", "DBB", "D-ALPHA-AMINOBUTYRIC ACID", ResidueType::withPolarHydrogen )} ,
    {"FGA", ChemicalPropertiesResidue("X", "FGA", "GAMMA-D-GLUTAMIC ACID", ResidueType::withPolarHydrogen )} ,
    {"SAH", ChemicalPropertiesResidue("X", "SAH", "S-ADENOSYL-L-HOMOCYSTEINE", ResidueType::withPolarHydrogen )} ,
    {"DLE", ChemicalPropertiesResidue("X", "DLE", "D-LEUCINE", ResidueType::withPolarHydrogen )} ,
    {"CME", ChemicalPropertiesResidue("X", "CME", "S,S-(2-HYDROXYETHYL)THIOCYSTEINE", ResidueType::withPolarHydrogen )} ,
    {"DPR", ChemicalPropertiesResidue("X", "DPR", "D-PROLINE", ResidueType::noPolarHydrogen )} ,
    {"FLC", ChemicalPropertiesResidue("X", "FLC", "CITRATE ANION", ResidueType::withPolarHydrogen )} ,
    {"3FG", ChemicalPropertiesResidue("X", "3FG", "(2S)-AMINO(3,5-DIHYDROXYPHENYL)ETHANOIC ACID", ResidueType::withPolarHydrogen )} ,
    {"LLP", ChemicalPropertiesResidue("X", "LLP", "2-LYSINE(3-HYDROXY-2-METHYL-5-PHOSPHONOOXYMETHYL-PYRIDIN-4-YLMETHANE)", ResidueType::withPolarHydrogen )} ,
    {"CSO", ChemicalPropertiesResidue("X", "CSO", "S-HYDROXYCYSTEINE", ResidueType::withPolarHydrogen )} ,
    {"OMY", ChemicalPropertiesResidue("X", "OMY", "(BETAR)-3-CHLORO-BETA-HYDROXY-L-TYROSINE", ResidueType::withPolarHydrogen )} ,
    {"M3L", ChemicalPropertiesResidue("X", "M3L", "N-TRIMETHYLLYSINE", ResidueType::withPolarHydrogen )} ,
    {"OMZ", ChemicalPropertiesResidue("X", "OMZ", "(BETAR)-3-CHLORO-BETA-HYDROXY-D-TYROSINE", ResidueType::withPolarHydrogen )} ,
    {"MLU", ChemicalPropertiesResidue("X", "MLU", "N-METHYL-D-LEUCINE", ResidueType::withPolarHydrogen )} ,
    {"FME", ChemicalPropertiesResidue("X", "FME", "N-FORMYLMETHIONINE", ResidueType::withPolarHydrogen )} ,
    {"DBU", ChemicalPropertiesResidue("X", "DBU", "(2Z)-2-AMINOBUT-2-ENOIC ACID", ResidueType::withPolarHydrogen )} ,
    {"DHA", ChemicalPropertiesResidue("X", "DHA", "2-AMINO-ACRYLIC ACID", ResidueType::withPolarHydrogen )} ,
    {"KCX", ChemicalPropertiesResidue("X", "KCX", "LYSINE NZ-CARBOXYLIC ACID", ResidueType::withPolarHydrogen )} ,
    {"MLE", ChemicalPropertiesResidue("X", "MLE", "N-METHYLLEUCINE", ResidueType::withPolarHydrogen )} ,
    {"NLE", ChemicalPropertiesResidue("X", "NLE", "NORLEUCINE", ResidueType::withPolarHydrogen )} ,
    {"DTR", ChemicalPropertiesResidue("X", "DTR", "D-TRYPTOPHAN", ResidueType::withPolarHydrogen )} ,
    {"SAM", ChemicalPropertiesResidue("X", "SAM", "S-ADENOSYLMETHIONINE", ResidueType::withPolarHydrogen )} ,
    {"ALY", ChemicalPropertiesResidue("X", "ALY", "N(6)-ACETYLLYSINE", ResidueType::withPolarHydrogen )} ,
    {"ACB", ChemicalPropertiesResidue("X", "ACB", "3-METHYL-BETA-D-ASPARTIC ACID", ResidueType::withPolarHydrogen )}

};



